# 1. Import Library

In [43]:
import pandas as pd
import pyarrow.parquet as pq
import geopandas as gpd
import requests

# 2. Membuat Parquet

membuat file parquet untuk tiap csv

In [44]:
# df_1 = pd.read_csv("datasets/yellow_tripdata_2016-01-02-03/yellow_tripdata_2016-01.csv")
# df_2 = pd.read_csv("datasets/yellow_tripdata_2016-01-02-03/yellow_tripdata_2016-02.csv")
# df_3 = pd.read_csv("datasets/yellow_tripdata_2016-01-02-03/yellow_tripdata_2016-03.csv")

# df_1.to_parquet(
#     "datasets/yellow_tripdata_parquet/yellow_tripdata_2016-01.parquet",
#     engine="pyarrow",
#     compression="snappy",
#     index=False
# )
# df_2.to_parquet(
#     "datasets/yellow_tripdata_parquet/yellow_tripdata_2016-02.parquet",
#     engine="pyarrow",
#     compression="snappy",
#     index=False
# )
# df_3.to_parquet(
#     "datasets/yellow_tripdata_parquet/yellow_tripdata_2016-03.parquet",
#     engine="pyarrow",
#     compression="snappy",
#     index=False
# )

# 3. Test Parquet terbuat

In [45]:
df = pd.read_parquet("data/parquet/2026/yellow_tripdata_2026-01.parquet")
df_zone = pd.read_csv("data/zone/taxi_zone_lookup.csv")
display(df.head(10))
display(df_zone.head(10))
df.info()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75
5,2,2026-01-01 00:47:11,2026-01-01 01:00:47,2.0,2.33,1.0,N,144,137,1,14.2,1.00,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
6,1,2026-01-01 00:17:54,2026-01-01 00:28:32,1.0,1.30,1.0,N,142,50,2,11.4,4.25,0.5,0.00,0.0,1.0,17.15,2.5,0.0,0.75
7,1,2026-01-01 00:34:28,2026-01-01 00:59:05,0.0,2.90,1.0,N,50,234,1,22.6,4.25,0.5,5.65,0.0,1.0,34.00,2.5,0.0,0.75
8,2,2026-01-01 00:34:14,2026-01-01 01:11:58,1.0,5.34,1.0,N,161,45,1,37.3,1.00,0.5,8.61,0.0,1.0,51.66,2.5,0.0,0.75
9,2,2026-01-01 00:41:07,2026-01-01 00:50:42,3.0,1.83,1.0,N,237,263,1,10.7,1.00,0.5,2.36,0.0,1.0,18.06,2.5,0.0,0.00

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone

<class 'pandas.DataFrame'>
RangeIndex: 3724889 entries, 0 to 3724888
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 528.5 MB

# 4. Mengubah SHP menjadi long lat pada PUloc dan DOloc

In [46]:
# # 1. Path ke file shapefile lokal kamu
# shp_path = r"data\zone\taxi_zones\taxi_zones.shp"

# # 2. Baca shapefile
# gdf = gpd.read_file(shp_path)

# # 3. Ubah proyeksi peta ke format standar GPS (WGS84 / EPSG:4326)
# gdf_gps = gdf.to_crs(epsg=4326)

# # 4. Hitung titik tengah (centroid) dari tiap poligon zona
# gdf_gps['longitude'] = gdf_gps.geometry.centroid.x
# gdf_gps['latitude'] = gdf_gps.geometry.centroid.y

# # 5. Ambil kolom LocationID dan koordinatnya
# coords_df = gdf_gps[['LocationID', 'latitude', 'longitude']].copy()

# # 6. Merge/gabungkan ke DataFrame zona kamu (misal nama variabelnya df_zone)
# df_zone_with_coords = pd.merge(
#     df_zone, 
#     coords_df, 
#     on='LocationID', 
#     how='left'
# )

# # Tampilkan hasil
# print(df_zone_with_coords.head())

## 4.1 Display Koordinat

In [47]:
# display(df_zone_with_coords)

# # Membersihkan data NaN
# df_zone_with_coords.dropna(inplace=True)

# display(df_zone_with_coords)

# df_zone_with_coords.to_parquet(
#     "data/zone/taxi_zone.parquet",
#     engine="pyarrow",
#     compression="snappy",
#     index=False
# )

## 4.2 Testing Taxi Zone Parquet

In [48]:
df_zone_parquet = pd.read_parquet(r"data\zone\taxi_zone.parquet")

display(df_zone_parquet.head(10))

,LocationID,Borough,Zone,service_zone,latitude,longitude
0,1,EWR,Newark Airport,EWR,40.691831,-74.174000
1,2,Queens,Jamaica Bay,Boro Zone,40.616745,-73.831299
2,3,Bronx,Allerton/Pelham Gardens,Boro Zone,40.864474,-73.847422
3,4,Manhattan,Alphabet City,Yellow Zone,40.723752,-73.976968
4,5,Staten Island,Arden Heights,Boro Zone,40.552659,-74.188484
5,6,Staten Island,Arrochar/Fort Wadsworth,Boro Zone,40.600324,-74.071771
6,7,Queens,Astoria,Boro Zone,40.761493,-73.919694
7,8,Queens,Astoria Park,Boro Zone,40.778559,-73.923086
8,9,Queens,Auburndale,Boro Zone,40.751035,-73.787949
9,10,Queens,Baisley Park,Boro Zone,40.678953,-73.790986

# 5. Merge Each Tripdata with Zone Parquet

In [49]:
# 1. Buat dictionary mapping dari coords_df yang udah kita buat tadi
lat_dict = df_zone_parquet.set_index('LocationID')['latitude'].to_dict()
lon_dict = df_zone_parquet.set_index('LocationID')['longitude'].to_dict()

# 2. Buat kolom koordinat penjemputan (Pick Up)
df['pickup_latitude'] = df['PULocationID'].map(lat_dict)
df['pickup_longitude'] = df['PULocationID'].map(lon_dict)

# 3. Buat kolom koordinat penurunan (Drop Off)
df['dropoff_latitude'] = df['DOLocationID'].map(lat_dict)
df['dropoff_longitude'] = df['DOLocationID'].map(lon_dict)

# 4. Hapus kolom ID lama (PULocationID & DOLocationID) kalau mau diganti total
df = df.drop(columns=['PULocationID', 'DOLocationID'])

# Cek hasil 5 baris pertama
print(df[['pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude']].head())

   pickup_latitude  pickup_longitude  dropoff_latitude  dropoff_longitude
0        40.783961        -73.978632         40.791705         -73.973049
1        40.764421        -73.977569         40.756688         -73.972356
2        40.782478        -73.965554         40.768615         -73.965635
3        40.773633        -73.981532         40.709073         -74.003665
4        40.703358        -74.011515         40.720889         -73.996919

In [50]:
display(df.sample(10))

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude
1158147,2,2026-01-14 17:56:06,2026-01-14 18:06:56,1.0,1.62,1.0,N,1,12.1,2.50,...,0.00,1.0,20.10,2.5,0.00,0.00,40.791705,-73.973049,40.782478,-73.965554
2593149,2,2026-01-31 15:56:40,2026-01-31 16:07:31,1.0,3.84,1.0,N,1,17.7,0.00,...,0.00,1.0,26.94,2.5,0.00,0.75,40.765484,-73.954739,40.714733,-73.983025
1582679,1,2026-01-19 12:02:42,2026-01-19 12:12:27,1.0,1.10,1.0,N,1,10.0,3.25,...,0.00,1.0,18.45,2.5,0.00,0.75,40.764421,-73.977569,40.748497,-73.992438
1200919,2,2026-01-15 07:27:25,2026-01-15 07:40:30,1.0,2.38,1.0,N,1,14.9,0.00,...,0.00,1.0,18.40,0.0,0.00,0.00,NaN,NaN,40.801169,-73.937346
1731386,1,2026-01-21 07:10:52,2026-01-21 07:19:37,1.0,1.30,1.0,N,2,9.3,3.25,...,0.00,1.0,14.05,2.5,0.00,0.75,40.748497,-73.992438,40.756688,-73.972356
1698968,1,2026-01-20 18:49:46,2026-01-20 19:41:05,1.0,17.40,2.0,N,1,70.0,8.25,...,7.46,1.0,104.61,2.5,0.00,0.75,40.742279,-73.996971,40.646985,-73.786533
2135063,2,2026-01-25 08:52:01,2026-01-25 09:59:01,1.0,18.54,2.0,N,1,70.0,0.00,...,0.00,1.0,91.80,2.5,1.75,0.75,40.646985,-73.786533,40.764421,-73.977569
227949,2,2026-01-04 02:12:54,2026-01-04 02:21:22,1.0,1.22,1.0,N,1,10.0,1.00,...,0.00,1.0,18.90,2.5,0.00,0.75,40.727620,-73.985937,40.740337,-73.990458
2435882,2,2026-01-29 20:44:54,2026-01-29 20:49:52,2.0,0.56,1.0,N,1,6.5,1.00,...,0.00,1.0,14.70,2.5,0.00,0.75,40.727620,-73.985937,40.727620,-73.985937
1299935,1,2026-01-15 23:20:34,2026-01-15 23:29:37,1.0,1.50,1.0,N,1,10.7,4.25,...,0.00,1.0,18.45,2.5,0.00,0.75,40.736824,-73.984052,40.728340,-73.997380