# 1. Import Library

In [8]:
import pandas as pd

# 2. Audit Kelengkapan Dataset

Apakah dataset benar-benar lengkap 7 bulan januari sampai juni

In [9]:
df = {}  # 1. Inisialisasi dictionary untuk menampung DataFrame tiap bulan

for i in range(1, 7):
    # Format {i:02d} otomatis membuat angka 1-9 jadi '01', '02', dst.
    file_path = rf"..\data\parquet\2026\yellow_tripdata_2026-{i:02d}.parquet"
    
    try:
        df[i] = pd.read_parquet(file_path)
        print(f"Dataset Bulan {i} berhasil dimuat.")
    except FileNotFoundError:
        print(f"Dataset Bulan {i} gaada!!")

Dataset Bulan 1 berhasil dimuat.
Dataset Bulan 2 berhasil dimuat.
Dataset Bulan 3 berhasil dimuat.
Dataset Bulan 4 berhasil dimuat.
Dataset Bulan 5 berhasil dimuat.
Dataset Bulan 6 berhasil dimuat.

# 3. Informasi Tiap Dataset

Ukuran, Jumlah Baris, Jumlah Kolom

In [29]:
for i, data in df.items():
    print(f"\n{'='*20} DATASET BULAN {i} {'='*20}")
    print(f"Shape: {data.shape}")
    
    # Gabungkan baris teratas dan terbawah dalam 1 display
    display(pd.concat([data.head(1), data.tail(1)]))

==================== DATASET BULAN 1 ====================
Shape: (3724889, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.20,1.0,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
3724888,2,2026-01-31 23:43:12,2026-01-31 23:57:45,NaN,1.04,NaN,NaN,148,148,0,16.49,0.0,0.5,0.00,0.0,1.0,21.24,NaN,NaN,0.75

==================== DATASET BULAN 2 ====================
Shape: (3399866, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2026-02-01 00:05:57,2026-02-01 00:05:57,1.0,0.94,1.0,N,107,170,1,7.2,0.0,0.5,0.0,0.0,1.0,12.95,2.5,0.0,0.75
3399865,2,2026-02-28 23:13:53,2026-02-28 23:25:55,NaN,1.16,NaN,NaN,211,79,0,26.2,0.0,0.5,0.0,0.0,1.0,30.95,NaN,NaN,0.75

==================== DATASET BULAN 3 ====================
Shape: (3952451, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-03-01 00:02:26,2026-03-01 00:13:45,1.0,2.58,1.0,N,48,151,1,14.20,1.0,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75
3952450,2,2026-03-31 23:14:21,2026-03-31 23:20:55,NaN,0.99,NaN,NaN,148,4,0,8.19,0.0,0.5,0.00,0.0,1.0,12.94,NaN,NaN,0.75

==================== DATASET BULAN 4 ====================
Shape: (3831240, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2026-04-01 00:40:05,2026-04-01 00:52:44,1.0,2.80,1.0,N,237,68,1,15.60,4.25,0.5,4.25,0.0,1.0,25.6,2.5,0.0,0.75
3831239,2,2026-04-30 23:58:15,2026-05-01 00:25:54,NaN,6.38,NaN,NaN,246,42,0,47.92,0.00,0.5,0.00,0.0,1.0,58.0,NaN,NaN,0.75

==================== DATASET BULAN 5 ====================
Shape: (4090836, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-05-01 00:04:59,2026-05-01 00:32:48,1.0,7.51,1.0,N,138,37,2,35.90,6.0,0.5,0.0,0.0,1.0,45.40,0.0,2.0,0.0
4090835,2,2026-05-31 23:41:51,2026-05-31 23:47:32,NaN,0.83,NaN,NaN,255,112,0,7.02,0.0,0.5,0.0,0.0,1.0,8.52,NaN,NaN,0.0

==================== DATASET BULAN 6 ====================
Shape: (3837248, 21)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,request_source
0,1,2026-06-01 00:04:22,2026-06-01 00:20:19,1.0,2.90,1.0,N,140,238,1,...,3.5,0.5,6.4,0.0,1.0,27.70,2.5,0.0,0.00,NaN
3837247,2,2026-06-30 23:50:27,2026-07-01 00:12:52,NaN,8.02,NaN,NaN,100,116,0,...,0.0,0.5,0.0,0.0,1.0,34.94,NaN,NaN,0.75,HV0003

# 4. Rentang Waktu Tiap Dataset

# 5. Memeriksa apakah nama kolom dan tipe data konsisten antarbulan

In [27]:
pick_columns = df[1].columns

print(f"Expected Column yang harusnya ada: \n{pick_columns}")

expected_set = set(pick_columns)

# 2. Cek tiap DataFrame di dictionary `df`
for i, data in df.items():
    actual_set = set(data.columns)
    
    # Cari kolom yang kurang atau kelebihan
    missing = expected_set - actual_set
    extra = actual_set - expected_set
    
    if not missing and not extra:
        print(f"Dataset Bulan {i}: Josjis, kolom lengkap ")
    else:
        print(f"Dataset Bulan {i}: [Warning] - ada ketidaksesuaian kolom!")
        if missing:
            print(f"   - Kurang (Missing): {missing}")
        if extra:
            print(f"   - Kelebihan (Extra): {extra}")

Expected Column yang harusnya ada:
Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='str')
Dataset Bulan 1: Josjis, kolom lengkap
Dataset Bulan 2: Josjis, kolom lengkap
Dataset Bulan 3: Josjis, kolom lengkap
Dataset Bulan 4: Josjis, kolom lengkap
Dataset Bulan 5: Josjis, kolom lengkap
Dataset Bulan 6: [Warning] - ada ketidaksesuaian kolom!
   - Kelebihan (Extra): {'request_source'}

# 6. Missing Someone Special

 Memeriksa kolom yang seluruh nilainya kosong atau hanya tersedia pada bulan tertentu.

# 7. Kenapa Dataset ini sesuai dengan kebutuhan latihan kedepannya?